package arquivo.services;

import java.util.List;

public class Keywords {

    public static final List<String> contextualKeywords = List.of(
            "25 de abril",
            "abril de 1974",
            "alentejo rural",
            "antifascismo",
            "assembleia constituinte",
            "capitães de abril",
            "censura",
            "clandestinidade",
            "comissões de trabalhadores",
            "comunicado do mfa",
            "descolonização",
            "emigração clandestina",
            "estado corporativo",
            "estado novo",
            "exílio político",
            "frente nacional",
            "guerra colonial",
            "grândola vila morena",
            "integração nacional",
            "jornais clandestinos",
            "liberdade de imprensa",
            "marcelo caetano",
            "mfa",
            "movimento das forças armadas",
            "mud",
            "nova constituição de 1976",
            "ocupações de terras",
            "oposição democrática",
            "pide",
            "pide-dgs",
            "portugal 1974",
            "prec",
            "prisão política",
            "processo revolucionário em curso",
            "reforma agrária",
            "reformas marcelistas",
            "regime de marcelo caetano",
            "regime de salazar",
            "regime do estado novo",
            "repressão política",
            "resistência antifascista",
            "revolução de 1974",
            "revolução de abril",
            "revolução dos cravos",
            "salazarismo",
            "salazarista",
            "tortura"
    );
}
