############################################################################
############################################################################
# Auxiliary services definitions
#
# This is not meant to be run directly, but to be used as base definitions
# referenced from other docker compose files (with 'extends' clause).
############################################################################
services:

  postgres:
    image: postgres:17.4
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=arquivo-db
    volumes:
      - ../db:/docker-entrypoint-initdb.d

  yake:
    image: liaad/yake-server:latest
    restart: always
    ports:
      - "5000:5000"

  kafka:
    image: bitnami/kafka:4.0.0
    container_name: kafka
    ports:
      - "9092:9092"  # Internal communication
      - "9093:9093"  # External access
    environment:
      # Enable KRaft Mode
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - ALLOW_PLAINTEXT_LISTENER=yes
      # Performance optimizations
      - KAFKA_CFG_LOG_RETENTION_HOURS=48  # Reduce log retention for smaller storage
      - KAFKA_CFG_LOG_RETENTION_BYTES=1073741824  # 1GB log size per topic-partition
      - KAFKA_CFG_NUM_PARTITIONS=3  # Default partitions per topic
      - KAFKA_CFG_NUM_NETWORK_THREADS=3  # Improve networking efficiency
      - KAFKA_CFG_NUM_IO_THREADS=8  # Optimize IO threads
      - KAFKA_CFG_SOCKET_SEND_BUFFER_BYTES=102400  # Tune socket buffers
      - KAFKA_CFG_SOCKET_RECEIVE_BUFFER_BYTES=102400
      - KAFKA_CFG_SOCKET_REQUEST_MAX_BYTES=104857600
      - KAFKA_CFG_REPLICA_LAG_TIME_MAX_MS=10000  # Reduce leader election delays
      - KAFKA_CFG_UNCLEAN_LEADER_ELECTION_ENABLE=false  # Ensure data integrity
      - KAFKA_CFG_MESSAGE_MAX_BYTES=10485760  # Allow larger message sizes
      - KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR=1  # Single-node setup requires this
      - KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=1  # Reduce unnecessary replication
      - KAFKA_CFG_MIN_INSYNC_REPLICAS=1  # Avoid producer rejections in single-node
      - KAFKA_CFG_GROUP_INITIAL_REBALANCE_DELAY_MS=0
      - KAFKA_CFG_GROUP_MIN_SESSION_TIMEOUT_MS=5000
      - KAFKA_CFG_GROUP_MAX_SESSION_TIMEOUT_MS=30000
      - KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR=1

    volumes:
      - kafka_data:/bitnami/kafka

volumes:
  kafka_data:
    driver: local