services:
  db:
    image: postgres:17.4
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: arquivo-db
    ports:
      - "5432:5432"
    volumes:
      - ../db:/docker-entrypoint-initdb.d

  backend:
    image: arquivo-rest  # Use your custom backend image
    container_name: arquivo-rest
    restart: always
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: arquivo-db
    ports:
      - "8080:8080"

  frontend:
    image: arquivo-web  # Use your custom frontend image
    container_name: arquivo-web
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: "http://localhost:8080"

volumes:
  pgdata:
